### PR TITLE
Added Chris' last publication

### PR DESCRIPTION
**Pull request by Fontanapink**

### CODE REVIEW

**Comment by JMante1** [comment]
There is an error in the deploy and the paper has no tags. I think that needs to be fixed before it can be merged in

**Comment by JMante1** [comment]
The error is: Error: Error building site: failed to render pages: render of "page" failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/wowchemy/wowchemy-hugo-modules/wowchemy@v0.0.0-20201001144923-e58ee0ffc576/layouts/publication/single.html:14:47": execute of template failed: template: publication/single.html:14:47: executing "main" at <index .Params.publication_types 0>: error calling index: index of untyped nil

So presumably the publication/single.html is causing problems. It may be having problems not having params.publication_types?

**Comment by Fontanapink** [comment]
solved for the errors. Now need a reviewer to approve

**Review by JMante1 — CHANGES_REQUESTED** [review]
Add tags before merging in. Probably best to add tags in Zotero

**Comment by Fontanapink** [comment]
Added

**Review by JMante1 — APPROVED** [review]

**Pull request merged**
