### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by LukasBuecherl**
Added Dissertation

### CODE REVIEW

**Review by cjmyers — APPROVED** [review]

**Comment by cjmyers** [comment]
Did we not upload files for other dissertations, so we had local copies?

**Comment by LukasBuecherl** [comment]
I just checked and Jet has a PDF linked and Pedro has nothing linked. I added a link to ProQuest since it seems the easiest and people with access to the university can download the pdf.

**Comment by cjmyers** [comment]
I would prefer Jet's approach, since this makes is fully open and accessible to all.  I will bug Pedro.

**Comment by LukasBuecherl** [comment]
Jet did some hacking with adding an author named "this link will open in a new window Link to external site". I was not able to get it to work quickly and am not a fan of the solution really. Maybe Pedro has more luck?

Screenshot 2024-11-05 at 16 20 38

**Pull request merged**
